### ISSUE TITLE
NYC Filter

### ISSUE THREAD

**Issue by katyfv** [ptucker6291/covid-dashboard-app#1]
Description: NYC is found within list of 50 states in dropdown selection.
Test Case ID: #181335429
Priority: Medium

**Comment by katyfv** [comment]
Description: Users are able to add additional values at end of URL. This enables the dashboard to filter on given "X" values.
Test Case ID:#181335440
Priority: Medium

**Comment by ptucker6291** [comment]
Both issues have been resolved in the following commit: https://github.com/ptucker6291/covid-dashboard-app/commit/5628f810b5f13c13a13ab19f407346c2aba398a0

I am closing the Issue.
